#!/usr/bin/env bash
# Summary: List hook scripts for a given phpenv command
# Usage: phpenv hooks <command>

set -e
[ -n "$PHPENV_DEBUG" ] && set -x

# Provide phpenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

PHPENV_COMMAND="$1"
if [ -z "$PHPENV_COMMAND" ]; then
  phpenv-help --usage hooks >&2
  exit 1
fi

IFS=: read -r -a hook_paths <<<"$PHPENV_HOOK_PATH"

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$PHPENV_COMMAND"/*.bash; do
    echo "$script"
  done
done
shopt -u nullglob
